#!/usr/bin/env zsh

# Prompt colors
ZSH_PROMPT_BOLD=true
ZSH_PROMPT_COLOR_MAIN="$FG[032]"
ZSH_PROMPT_COLOR_MAIN_RIGHT="$FG[237]"
ZSH_PROMPT_COLOR_GIT_MAIN="$FG[190]"
ZSH_PROMPT_COLOR_GIT_UNTRACKED="$FG[200]"
ZSH_PROMPT_COLOR_GIT_AHEAD="$FG[014]"
ZSH_PROMPT_COLOR_GIT_BEHIND="$FG[166]"
ZSH_PROMPT_COLOR_GIT_SEP="$FG[190]"
ZSH_PROMPT_COLOR_NO_SUCCESS="$FG[200]"


# Setup our prompts
precmd() {
    if [ -n "$TMUX" ]; then
        # Restore tmux-title to 'zsh'
        printf "\033kzsh $(short_pwd)\033\\"
        # Tell tmux to update the status bar
        tmux refresh-client -S
    fi

	PS1="%{${ZSH_PROMPT_COLOR_MAIN}%}"

	if $ZSH_PROMPT_BOLD; then
		PS1+="%{$FX[bold]%}"
	fi

	PS1+="%3~%{$ZSH_PROMPT_COLOR_MAIN%} %(0?..%{${ZSH_PROMPT_COLOR_NO_SUCCESS}%})%(!.#.%%)%{${reset_color}$FX[reset]%} "
}

preexec() {
    if [ -n "$TMUX" ]; then
        # set tmux-title to running program
        printf "\033k$(echo "$1" | cut -d" " -f1) $(short_pwd)\033\\"
    fi
}
