#!/bin/sh

CONFIG_DIR=$(pwd)/config

filelist=()
for file in $(ls -a $CONFIG_DIR)
do
	if [ -f "$CONFIG_DIR/$file" ]; then
		filelist[${#filelist[@]}]=$file
	fi
done


show_help() {
	echo "Commands:"
	echo "\t install - Installs symlinks to config"
	echo "\t clean - Removes symlinks to config"
}

install() {
	for file in ${filelist[@]}
	do
		echo "[INSTALL]: Adding $file to $HOME"
		ln -s $CONFIG_DIR/$file $HOME 2> /dev/null
	done

	echo "[INSTALL]: Adding Sublime Text 3 user settings"
	mkdir -p $HOME/Library/Application\ Support/Sublime\ Text\ 3/Packages
	cd $HOME/Library/Application\ Support/Sublime\ Text\ 3/Packages

	if [ -d "User" ]; then
		mv User User.backup
	fi

	ln -s $CONFIG_DIR/sublime User
}

clean() {
	for file in ${filelist[@]}
	do
		echo "[CLEAN]: Removing config $file from $HOME"
		rm $HOME/$file 2> /dev/null
	done


	cd $HOME/Library/Application\ Support/Sublime\ Text\ 3/Packages
	if [ -L "User" ]; then
		echo "[CLEAN]: Restoring Sublime Text 3 user settings"
		rm User

		if [ -d "User.backup" ]; then
			mv User.backup User
		fi
	fi
}

if [ `type -t $1`"" = "function" ]; then
	$1
else
	show_help
fi