<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>COMMIT_EDITMSG</string>
	</array>
	<key>name</key>
	<string>Git commit message</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^#.*</string>
			<key>name</key>
			<string>comment.line.git_commit</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^.+$</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.git_commit</string>
				</dict>
			</dict>
			<key>end</key>
			<string>[^\s\S]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^#.*</string>
					<key>name</key>
					<string>comment.line.git_commit</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.*</string>
					<key>name</key>
					<string>string.commit.git_commit</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.git_commit</string>
	<key>uuid</key>
	<string>86a62b56-668d-4d99-bc50-e4469e8f858f</string>
</dict>
</plist>
