#!/bin/sh

get_battery_percent() {
    if command -v pmset >& /dev/null; then
        pmset -g batt | awk 'NR==2 { gsub(/;/,""); print $2 }'
    elif command -v upower >& /dev/null; then
        for battery in $(upower -e | grep battery); do
            upower -i $battery | grep percentage | awk '{print $2}'
        done | xargs echo
    elif command -v acpi >& /dev/null; then
        acpi -b | grep -Eo "[0-9]+%"
    fi
}

raw_value=$(get_battery_percent | awk '{ print substr($0, 0, length($0)-1) }')
if [ $raw_value -gt 40 ]; then
    color="colour010"
elif [ $raw_value -gt 15 ]; then
    color="colour011"
else
    color="colour009"
fi

printf "#[fg=colour235,bg=${color},bold] %s%% #[bg=default]" "$raw_value"
