#!/bin/sh

# cd to the directory specified by the first argument
cd "$1"

if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "$2"
    exit
fi

# Sleep briefly to avoid race conditions with the index.lock file when stashing
sleep 0.1

REMOTE=$(git rev-list --left-right @{u}...)
AHEAD_COUNT=$(echo "${REMOTE}" | awk '/^>/{c++}END{print c}')
BEHIND_COUNT=$(echo "${REMOTE}" | awk '/^</{c++}END{print c}')
BRANCH=$(git rev-parse --abbrev-ref HEAD)
GIT_STATUS=$(git status --porcelain)

parts=()
flags=()

# Staged changes
if echo "$GIT_STATUS" | grep -q '^[ADMR]' >& /dev/null; then
    flags+=("🚀.")
fi

# Unstaged changes
if echo "$GIT_STATUS" | grep -q '^.[ADMR]' >& /dev/null; then
    flags+=("💥.")
fi

# Untracked changes
if echo "$GIT_STATUS" | grep -q '??' >& /dev/null; then
    flags+=("🔥.")
fi

parts+=($(IFS=; echo "${flags[*]}"))
parts+=($BRANCH)

if [ $AHEAD_COUNT -gt 0 ]; then
    parts+=("#[fg=colour014]↑${AHEAD_COUNT}")
fi

if [ $BEHIND_COUNT -gt 0 ]; then
    parts+=("#[fg=colour166]↓${BEHIND_COUNT}")
fi

echo " #[fg=colour190,bold]$(IFS=\ ; echo "${parts[*]}" | tr '.' ' ') "
